# Generated by Django 5.2 on 2025-05-31 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='currency',
            field=models.CharField(default='PLN', max_length=3),
        ),
    ]
