# Generated by Django 5.2 on 2025-05-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_goal_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='goaltransaction',
            name='currency',
            field=models.CharField(default='PLN', max_length=3),
        ),
        migrations.AddField(
            model_name='goaltransaction',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
    ]
